[package]
name = "owasm-abi"
version = "0.1.12"
authors = ["NikVolf <nikvolf@gmail.com>", "Oasis Labs <info@oasislabs.com"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/oasislabs/owasm-abi"
homepage = "https://github.com/oasislabs/owasm-abi"
documentation = "https://paritytech.github.io/pwasm-abi/pwasm_abi/"
description = "Rust WebAssembly Contracts Abi"
keywords = ["wasm", "parity", "webassembly", "blockchain", "abi"]
categories = ["no-std", "embedded"]
exclude = [ "tests/*", "derive/*" ]

[profile.release]
panic = "abort"

[dependencies]
pwasm-std = "0.10"

[dependencies.uint]
version = "0.4"
default-features = false

[dependencies.byteorder]
version = "1.2.3"
default-features = false

[dev-dependencies]
hex-literal = "0.1"

[features]
default = ["std"]
std = ["uint/std", "pwasm-std/std"]
strict = []
